// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.cache_locks */
export type CacheLocksKey = string & { __brand: 'CacheLocksKey' };

/** Represents the table public.cache_locks */
export default interface CacheLocks {
    key: CacheLocksKey;

    owner: string;

    expiration: number;
}

/** Represents the initializer for the table public.cache_locks */
export interface CacheLocksInitializer {
    key: CacheLocksKey;

    owner: string;

    expiration: number;
}

/** Represents the mutator for the table public.cache_locks */
export interface CacheLocksMutator {
    key?: CacheLocksKey;

    owner?: string;

    expiration?: number;
}
