// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.cache */
export type CacheKey = string & { __brand: 'CacheKey' };

/** Represents the table public.cache */
export default interface Cache {
    key: CacheKey;

    value: string;

    expiration: number;
}

/** Represents the initializer for the table public.cache */
export interface CacheInitializer {
    key: CacheKey;

    value: string;

    expiration: number;
}

/** Represents the mutator for the table public.cache */
export interface CacheMutator {
    key?: CacheKey;

    value?: string;

    expiration?: number;
}
