// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { RolesId } from './Roles';

/** Identifier type for public.model_has_roles */
export type ModelHasRolesModelType = string & { __brand: 'ModelHasRolesModelType' };

/** Identifier type for public.model_has_roles */
export type ModelHasRolesModelId = string & { __brand: 'ModelHasRolesModelId' };

/** Represents the table public.model_has_roles */
export default interface ModelHasRoles {
    role_id: RolesId;

    model_type: ModelHasRolesModelType;

    model_id: ModelHasRolesModelId;
}

/** Represents the initializer for the table public.model_has_roles */
export interface ModelHasRolesInitializer {
    role_id: RolesId;

    model_type: ModelHasRolesModelType;

    model_id: ModelHasRolesModelId;
}

/** Represents the mutator for the table public.model_has_roles */
export interface ModelHasRolesMutator {
    role_id?: RolesId;

    model_type?: ModelHasRolesModelType;

    model_id?: ModelHasRolesModelId;
}
