// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PermissionsId } from './Permissions';

/** Identifier type for public.model_has_permissions */
export type ModelHasPermissionsModelType = string & { __brand: 'ModelHasPermissionsModelType' };

/** Identifier type for public.model_has_permissions */
export type ModelHasPermissionsModelId = string & { __brand: 'ModelHasPermissionsModelId' };

/** Represents the table public.model_has_permissions */
export default interface ModelHasPermissions {
    permission_id: PermissionsId;

    model_type: ModelHasPermissionsModelType;

    model_id: ModelHasPermissionsModelId;
}

/** Represents the initializer for the table public.model_has_permissions */
export interface ModelHasPermissionsInitializer {
    permission_id: PermissionsId;

    model_type: ModelHasPermissionsModelType;

    model_id: ModelHasPermissionsModelId;
}

/** Represents the mutator for the table public.model_has_permissions */
export interface ModelHasPermissionsMutator {
    permission_id?: PermissionsId;

    model_type?: ModelHasPermissionsModelType;

    model_id?: ModelHasPermissionsModelId;
}
