// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.sessions */
export type SessionsId = string & { __brand: 'SessionsId' };

/** Represents the table public.sessions */
export default interface Sessions {
    id: SessionsId;

    user_id: string | null;

    ip_address: string | null;

    user_agent: string | null;

    payload: string;

    last_activity: number;
}

/** Represents the initializer for the table public.sessions */
export interface SessionsInitializer {
    id: SessionsId;

    user_id?: string | null;

    ip_address?: string | null;

    user_agent?: string | null;

    payload: string;

    last_activity: number;
}

/** Represents the mutator for the table public.sessions */
export interface SessionsMutator {
    id?: SessionsId;

    user_id?: string | null;

    ip_address?: string | null;

    user_agent?: string | null;

    payload?: string;

    last_activity?: number;
}
